### ISSUE TITLE
Transparency not Working Properly

### ISSUE THREAD

**Issue by I2pRandom** [Lylythii/BetterDiscordAddons#2]
For some reason Transparency does not work properly on Armcord with Vencord, resulting in the background of the client being opaque instead of transparency.
![2023-07-20_23-51](https://github.com/Lylythii/BetterDiscordAddons/assets/42506001/57a7692f-f256-4edd-a7bd-1de69e52a615)

**Comment by Lylythii** [comment]
From what I recall, Armcord doesn't support full transparency by default. Though [it can be enabled](https://github.com/ArmCord/ArmCord/issues/337) manually in the `settings.json`

Don't have it installed currently to check myself. Let me know & I'll add a note to the README!

**Comment by smartfrigde** [comment]
ArmCord 3.2.0 --> 3.2.1, changed how transparency works and now it requires Windows 11 22H2, make sure you have up-to-date OS
