### ISSUE TITLE
Transparency doesn't work :/

### ISSUE THREAD

**Issue by xlso23** [Lylythii/BetterDiscordAddons#3]
i'm on windows 11 and i use vencord, whenever i try to use the theme everything just becomes one collour like when i tried other glass themes, is there any way to solve the issue?

**Comment by Lylythii** [comment]
- Path to `C:\Users\YOUR_NAME\AppData\Roaming\Vencord\settings` & locate `settings.json`.
- On line `14`, change `"transparent": false` to `"transparent": true`.
- Restart Vencord.
